# Site settings
title: Jekyll Practice
email: j3robinson1@gmail.com
description: First time Jekyll
baseurl: "/Jekyll_Practice"
twitter_username: 
avatar: "https://avatars2.githubusercontent.com/u/10171543?v=3&u=f22db572c007926945972a8be2a6b3c8634210d1&s=140" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Jesse Robinson" # Set default author name
      categories: "sample"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
