# Site settings
title: Jekyll Practice
email: j3robinson1@gmail.com
description: First time Jekyll
baseurl: "/Jekyll_Practice"
twitter_username: 
avatar: "https://github.com/account" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Jesse Robinson" # Set default author name
      categories: "Random"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
